export const listaDeClientes = [
    {
      foto: 'url_da_foto1',
      nome: 'Ana Silva',
      projetosPendentes: 2,
      projetosEmAndamento: 3,
      projetosConcluidos: 5,
      instagram: 'url_do_instagram1',
      facebook: 'url_do_facebook1',
      site: 'url_do_site1',
      linkedin: 'url_do_linkedin1',
      email: 'ana@email.com',
      celular: '555-123-4567',
    },
    {
      foto: 'url_da_foto2',
      nome: 'Pedro Santos',
      projetosPendentes: 1,
      projetosEmAndamento: 4,
      projetosConcluidos: 6,
      instagram: 'url_do_instagram2',
      facebook: 'url_do_facebook2',
      site: 'url_do_site2',
      linkedin: '',
      email: 'pedro@email.com',
      celular: '555-987-6543',
    },
    {
      foto: 'url_da_foto3',
      nome: 'Luisa Oliveira',
      projetosPendentes: 3,
      projetosEmAndamento: 2,
      projetosConcluidos: 4,
      instagram: 'url_do_instagram3',
      facebook: '',
      site: '',
      linkedin: 'url_do_linkedin3',
      email: 'luisa@email.com',
      celular: '555-333-2222',
    },
    {
      foto: 'url_da_foto4',
      nome: 'Rafael Pereira',
      projetosPendentes: 0,
      projetosEmAndamento: 7,
      projetosConcluidos: 3,
      instagram: '',
      facebook: 'url_do_facebook4',
      site: 'url_do_site4',
      linkedin: 'url_do_linkedin4',
      email: 'rafael@email.com',
      celular: '555-777-8888',
    },
    {
      foto: 'url_da_foto5',
      nome: 'Mariana Costa',
      projetosPendentes: 4,
      projetosEmAndamento: 1,
      projetosConcluidos: 8,
      instagram: '',
      facebook: 'url_do_facebook5',
      site: '',
      linkedin: '',
      email: 'mariana@email.com',
      celular: '555-111-9999',
    },
    {
      foto: 'url_da_foto6',
      nome: 'Carlos Rodrigues',
      projetosPendentes: 2,
      projetosEmAndamento: 2,
      projetosConcluidos: 6,
      instagram: 'url_do_instagram6',
      facebook: '',
      site: 'url_do_site6',
      linkedin: '',
      email: 'carlos@email.com',
      celular: '555-222-4444',
    },
    {
      foto: 'url_da_foto7',
      nome: 'Isabela Fernandes',
      projetosPendentes: 1,
      projetosEmAndamento: 3,
      projetosConcluidos: 7,
      instagram: 'url_do_instagram7',
      facebook: 'url_do_facebook7',
      site: '',
      linkedin: '',
      email: 'isabela@email.com',
      celular: '555-444-5555',
    },
    {
      foto: 'url_da_foto8',
      nome: 'Gustavo Alves',
      projetosPendentes: 3,
      projetosEmAndamento: 1,
      projetosConcluidos: 6,
      instagram: 'url_do_instagram8',
      facebook: '',
      site: 'url_do_site8',
      linkedin: '',
      email: 'gustavo@email.com',
      celular: '555-888-3333',
    },
    {
      foto: 'url_da_foto9',
      nome: 'Fernanda Sousa',
      projetosPendentes: 2,
      projetosEmAndamento: 5,
      projetosConcluidos: 4,
      instagram: 'url_do_instagram9',
      facebook: 'url_do_facebook9',
      site: 'url_do_site9',
      linkedin: 'url_do_linkedin9',
      email: 'fernanda@email.com',
      celular: '555-999-1111',
    },
    {
      foto: 'url_da_foto10',
      nome: 'José Lima',
      projetosPendentes: 1,
      projetosEmAndamento: 6,
      projetosConcluidos: 3,
      instagram: 'url_do_instagram10',
      facebook: 'url_do_facebook10',
      site: '',
      linkedin: 'url_do_linkedin10',
      email: 'jose@email.com',
      celular: '555-777-2222',
    },
    {
      foto: 'url_da_foto11',
      nome: 'Patricia Santos',
      projetosPendentes: 4,
      projetosEmAndamento: 2,
      projetosConcluidos: 4,
      instagram: 'url_do_instagram11',
      facebook: '',
      site: 'url_do_site11',
      linkedin: 'url_do_linkedin11',
      email: 'patricia@email.com',
      celular: '555-666-3333',
    },
    {
      foto: 'url_da_foto12',
      nome: 'Antonio Mendes',
      projetosPendentes: 2,
      projetosEmAndamento: 4,
      projetosConcluidos: 5,
      instagram: '',
      facebook: 'url_do_facebook12',
      site: 'url_do_site12',
      linkedin: 'url_do_linkedin12',
      email: 'antonio@email.com',
      celular: '555-555-5555',
    },
  ];
  
  console.log(listaDeClientes);
  