export const listaDeClientes = [
  {
    nome: 'Ana Silva',
    projetosPendentes: 2,
    projetosEmAndamento: 3,
    projetosConcluidos: 5,
    instagram: 'https://www.instagram.com/nyckpetrova/',
    facebook: 'url_do_facebook1',
    site: 'url_do_site1',
    linkedin: 'https://www.linkedin.com/in/nycoleribeiro/',
    email: 'rpnyck@gmail.com',
    telefone: '555-123-4567',
    clientId: 1,
  },
  {
    nome: 'Pedro Santos',
    projetosPendentes: 1,
    projetosEmAndamento: 4,
    projetosConcluidos: 6,
    instagram: 'https://www.instagram.com/nyckpetrova/',
    facebook: 'url_do_facebook2',
    site: 'url_do_site2',
    linkedin: '',
    email: 'pedro@email.com',
    telefone: '555-987-6543',
    clientId: 2,
  },
  {
    nome: 'Luisa Oliveira',
    projetosPendentes: 3,
    projetosEmAndamento: 2,
    projetosConcluidos: 4,
    instagram: 'https://www.instagram.com/nyckpetrova/',
    facebook: '',
    site: '',
    linkedin: 'https://www.linkedin.com/in/nycoleribeiro/',
    email: 'luisa@email.com',
    telefone: '555-333-2222',
    clientId: 3,
  },
  {
    nome: 'Rafael Pereira',
    projetosPendentes: 0,
    projetosEmAndamento: 7,
    projetosConcluidos: 3,
    instagram: '',
    facebook: 'url_do_facebook4',
    site: 'url_do_site4',
    linkedin: 'https://www.linkedin.com/in/nycoleribeiro/',
    email: 'rafael@email.com',
    telefone: '555-777-8888',
    clientId: 4,
  },
  {
    nome: 'Mariana Costa',
    projetosPendentes: 4,
    projetosEmAndamento: 1,
    projetosConcluidos: 8,
    instagram: '',
    facebook: 'url_do_facebook5',
    site: '',
    linkedin: '',
    email: 'mariana@email.com',
    telefone: '555-111-9999',
    clientId: 5,
  },
  {
    nome: 'Carlos Rodrigues',
    projetosPendentes: 2,
    projetosEmAndamento: 2,
    projetosConcluidos: 6,
    instagram: 'https://www.instagram.com/nyckpetrova/',
    facebook: '',
    site: 'url_do_site6',
    linkedin: '',
    email: 'carlos@email.com',
    telefone: '555-222-4444',
    clientId: 6,
  },
  {
    nome: 'Isabela Fernandes',
    projetosPendentes: 1,
    projetosEmAndamento: 3,
    projetosConcluidos: 7,
    instagram: 'https://www.instagram.com/nyckpetrova/',
    facebook: 'url_do_facebook7',
    site: '',
    linkedin: '',
    email: 'isabela@email.com',
    telefone: '555-444-5555',
    clientId: 7,
  },
  {
    nome: 'Gustavo Alves',
    projetosPendentes: 3,
    projetosEmAndamento: 1,
    projetosConcluidos: 6,
    instagram: 'https://www.instagram.com/nyckpetrova/',
    facebook: '',
    site: 'url_do_site8',
    linkedin: '',
    email: 'gustavo@email.com',
    telefone: '555-888-3333',
    clientId: 8,
  },
  {
    nome: 'Fernanda Sousa',
    projetosPendentes: 2,
    projetosEmAndamento: 5,
    projetosConcluidos: 4,
    instagram: 'https://www.instagram.com/nyckpetrova/',
    facebook: 'url_do_facebook9',
    site: 'url_do_site9',
    linkedin: 'https://www.linkedin.com/in/nycoleribeiro/',
    email: 'fernanda@email.com',
    telefone: '555-999-1111',
    clientId: 9,
  },
  {
    nome: 'José Lima',
    projetosPendentes: 1,
    projetosEmAndamento: 6,
    projetosConcluidos: 3,
    instagram: 'https://www.instagram.com/nyckpetrova/',
    facebook: 'url_do_facebook10',
    site: '',
    linkedin: 'https://www.linkedin.com/in/nycoleribeiro/',
    email: 'jose@email.com',
    telefone: '555-777-2222',
    clientId: 10,
  },
  {
    nome: 'Patricia Santos',
    projetosPendentes: 4,
    projetosEmAndamento: 2,
    projetosConcluidos: 4,
    instagram: 'https://www.instagram.com/nyckpetrova/',
    facebook: '',
    site: 'url_do_site11',
    linkedin: 'https://www.linkedin.com/in/nycoleribeiro/',
    email: 'patricia@email.com',
    telefone: '555-666-3333',
    clientId: 11,
  },
  {
    nome: 'Antonio Mendes',
    projetosPendentes: 2,
    projetosEmAndamento: 4,
    projetosConcluidos: 5,
    instagram: '',
    facebook: 'url_do_facebook12',
    site: 'url_do_site12',
    linkedin: 'https://www.linkedin.com/in/nycoleribeiro/',
    email: 'antonio@email.com',
    telefone: '555-555-5555',
    clientId: 12,
  },
];
